spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fampro
    username: fampro
    password: W3isg3rb3r
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true